export const VEHICLES = [
    "50", "51", "52", "53", "55", "56", "58", "60", "61", "62", "63",
    "ダイヤ1", "ダイヤ2", "ダイヤ3"
];

export const PICKUP_LOCATIONS = [
    { name: "新光", reading: "しんこう" },
    { name: "ヒラバヤシ", reading: "ひらばやし" },
    { name: "サンコーH", reading: "さんこーH" },
    { name: "ヤマカ", reading: "やまか" },
    { name: "回転", reading: "かいてん" },
    { name: "コーエー", reading: "こーえー" },
    { name: "黒田", reading: "くろだ" },
    { name: "伸和", reading: "しんわ" },
    { name: "GP", reading: "じーぴー" },
    { name: "新町", reading: "しんまち" },
    { name: "飯山F", reading: "いいやまF" },
    { name: "クマイ", reading: "くまい" },
    { name: "高松", reading: "たかまつ" },
    { name: "SE富士見", reading: "えすいーふじみ" },
    { name: "ダイドー", reading: "だいどー" },
    { name: "つるみね", reading: "つるみね" },
    { name: "豊科RC", reading: "とよしなRC" },
    { name: "弥生精工", reading: "やよいせいこう" },
    { name: "島田製作所", reading: "しまだせいさくしょ" },
    { name: "三全精工", reading: "さんぜんせいこう" },
    { name: "サンホタカ", reading: "さんほたか" },
    { name: "中村M", reading: "なかむらM" },
    { name: "オタリGAC", reading: "おたりGAC" },
    { name: "阿部電機", reading: "あべでんき" },
    { name: "ヤマカ精工", reading: "やまかせいこう" },
    { name: "内山精工", reading: "うちやませいこう" },
    { name: "猪又", reading: "いのまた" },
    { name: "トライアン", reading: "とらいあん" },
    { name: "サンコー", reading: "さんこー" },
    { name: "カワイ", reading: "かわい" },
    { name: "大和", reading: "やまと" },
    { name: "IHI大桑", reading: "IHIおおくわ" },
    { name: "IHI回転", reading: "IHIかいてん" },
    { name: "泉", reading: "いずみ" },
    { name: "猪俣", reading: "いのまた" },
    { name: "トーエネック", reading: "とーえねっく" },
    { name: "小林鋼材", reading: "こばやしこうざい" },
    { name: "信越ポリマ", reading: "しんえつぽりま" },
    { name: "清水口Fe", reading: "しみずぐちFe" },
    { name: "南安", reading: "なんあん" },
    { name: "しなのフジ", reading: "しなのふじ" },
    { name: "CMCS", reading: "CMCS" },
    { name: "一陽", reading: "いちよう" },
    { name: "ホーマー", reading: "ほーまー" },
    { name: "コパル", reading: "こぱる" },
    { name: "回転ホッパー", reading: "かいてんほっぱー" }
];
